name: 🐛 错误报告
description: "报告软件中的错误或异常行为。"
title: "请输入Bug标题"
body:
  - type: markdown
    attributes:
      value: |
        插件为个人自用，开源只是分享，不等于我要浪费我的时间免费帮用户实现 ta 需要的功能。

        我需要的功能我会慢慢改进（打赏可以催更）；有些我觉得可以改进但现阶段不必要的功能，需要打赏才考虑实现（会标注“打赏”标签和所需金额）；我不需要的功能或实现成本极高的功能会直接关闭 issue，不予考虑。我没实现的功能欢迎有大佬来pr。

        请不要不经思考随意提大量 issue，因为这会打扰到我并浪费我的时间。
  - type: checkboxes
    attributes:
      label: 是否已 Star 本仓库？
      description: 未 Star 的用户 Issue 会被直接关闭。
      options:
        - label: 我已 Star 本仓库
          required: true
  - type: checkboxes
    attributes:
      label: 是否已搜索现有 Issue？
      description: |
        请先在现有 Issue 中搜索，避免重复提交相同问题。
      options:
        - label: 我已搜索过现有 Issue
          required: true
  - type: checkboxes
    attributes:
      label: 是否能在默认主题（白天/夜间）复现？
      description: |
        请确认该问题是否在默认主题下可复现，便于排查与主题相关的问题。
      options:
        - label: 我在默认主题下能复现该问题
          required: true
  - type: checkboxes
    attributes:
      label: 是否排除扩展影响？
      description: |
        主题、代码片段、插件等扩展可能导致问题，请尽量排除扩展影响后再提交问题。
      options:
        - label: 我已排除扩展导致问题的可能性
          required: true
  - type: textarea
    attributes:
      label: 问题描述（必须）
      description: |
        请尽可能清晰地描述遇到的问题、出现频率及出现时间点。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 期望结果（必须）
      description: |
        请清楚描述你期望得到的正确行为或结果。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或录像（可选）
      description: |
        请尽量附上截图或录屏，能更快定位问题。
    validations:
      required: false
  - type: textarea
    attributes:
      label: 版本与环境（必须）
      value: |
        - 版本：
        - 操作系统：
        - 浏览器（若使用）：
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: 是否愿意打赏（必须，若愿意请说明金额）
      description: |
        为了加速实现，可选打赏支持，已打赏issue的处理优于未打赏。
        请按规范填写，不愿意打赏就填「不愿意」，愿意打赏，请填写「愿意+具体金额」，过去已打赏需要填写「已打赏+过去打赏大体总额」，不按照规范填写issue会被直接关闭。
        为本项目PR贡献代码的大佬可填「PR贡献者」
        ![打赏链接](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241128221208-2024-11-28.png)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 其他信息（可选）
      description: |
        如有其他可帮助诊断的信息（网络状况、重现步骤、特殊配置等），请一并提供。
    validations:
      required: false